apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Release.Name }}-{{ .Values.global.env }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.global.labels }}
  labels:
  {{ toYaml .Values.global.labels | indent 2 }}
  {{ end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-{{ .Release.Name }}-{{ .Values.global.env }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
{{- if .Values.hpa.metrics }}
  metrics:
{{ toYaml .Values.hpa.metrics | indent 4 }}
{{- end }}