apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Release.Name }}-{{ .Values.global.env }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.global.labels }}
  labels:
  {{ toYaml .Values.global.labels | indent 2 }}
  {{ end }}
type: Opaque
data:
{{- range $key, $value := index .Values.variables.secret }}
  {{ $value.name }}: {{ $value.value }}
{{- end }}