apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}-{{ .Values.global.env }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.global.labels }}
  labels:
  {{ toYaml .Values.global.labels | indent 2 }}
  {{ end }}
spec:
  ports:
  {{- range $key, $value := .Values.app.ports }}
      - name: http-{{ $.Release.Name }}
        port: {{ $value.servicePort}}
        targetPort: {{ $value.name }}
        protocol: {{ $value.protocol }}
  {{- end }}
  selector:
  {{ toYaml .Values.global.labels | indent 2 }}